baseURL       = "https://www.tanzraum.ch/"
languageCode  = "ch-de"
title         = "TanzRaum | Official"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Start"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Veranstaltungen"
    url     = "veranstaltungen"
    weight  = 2
  [[menu.nav]]
    name    = "Raum"
    url     = "raum"
    weight  = 3
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "TanzRaum | Offizieller Webauftritt"
  author = "TanzRaum"
  # Google Analitycs
  googleAnalitycsID = "Your ID"

  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Kontakt"
    url     = "kontakt"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/raum.jpeg"
    heading               = "We’re a Design Studio That Belies In the Great Ideas"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "Veranstaltungen"
    primary_button_url    = "veranstaltungen"
    secondary_button      = "Raum"
    secondary_button_url  = "raum"
    arrowlink             = ""

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "/images/backgrounds/cta-background.jpg"
    title               = "Kontakt"
    form_heading        = "Kontaktformular"
    # We're using formspree.io for form handling, paste your formspree url below
    formspreeFormUrl  = "https://formspree.io/f/mvovrryp"


  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Kontaktinfromationen"
      address = "Mühlebühl 16a<br>9100 Herisau"
      phone   = "+41 79 463 85 43"
      email   = "info@tanzraum.ch"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"